allowed-commands:
  - "msg"
  - "mail"
  - "home"
  - "sethome"
  - "skills"
  - "status"
  - "jobs"
  - "tpa"
  - "tpr"
  - "pay"
  - "qs"
  - "paytoggle"
  - "balancetop"
  - "balance"
  - "money"
  - "nation"
  - "towny"
  - "town"
  - "townychat"
  - "coreprotect"
  - "co"
  - "ec"

